### ISSUE TITLE
Job Status Notification.

### ISSUE THREAD

**Issue by monalisir** [scrapy/scrapyd#199] opened 2017-01-05 01:24 UTC
Is there any way to notify client which job has been finished ?
So the client do not need to add a timer and check the status every period time.

**Comment by Digenis** [comment] 2017-01-05 16:48
There is ticket for this, #55, which is low on the priority list
until more users show interest andor someone comes up with a nice PR.

I see two alternatives.
You can either write an extension
and use it in all your deployed projects,
which should be simple for 1-2 projects,
or write a custom [launcher](https://github.com/scrapy/scrapyd/blob/1.1/scrapyd/launcher.py)
and [configure](https://github.com/scrapy/scrapyd/blob/1.1/scrapyd/default_scrapyd.conf#L15) your scrapyd to use it.

**Comment by my8100** [comment] 2018-12-03 06:54
The third alternatives would be [ScrapydWeb](https://github.com/my8100/scrapydweb), and get email notified when a job is finished.

**Comment by jeromecaisip** [comment] 2019-02-07 03:27
@Digenis If you don't mind. How are you able to add a path on the scrapyd.conf so I can use my launcher class on my module. Thanks.

**Comment by Digenis** [comment] 2019-04-16 17:46
Hi @jeromecaisip,

Make a package for your launcher module with setuptools
https://setuptools.readthedocs.io/en/latest/setuptools.html

Install it in the python environment in which scrapyd runs
 eg `pip install git+file:///home/jerome/proprietary-scrapyd-plugins/`

Define the path in your scrapyd configuration.
```
[scrapyd]
launcher = proprietary_scrapyd_plugins.launcher.Launcher
```

This seems to be common question.
Consider contributing a tutorial to the mailing list or a wiki.

**Comment by jpmckinney** [comment] 2021-09-23 14:44
Closing as duplicate of #55.

**Closed by jpmckinney** 2021-09-23 14:44 UTC
Labels: status: duplicate
