### ISSUE TITLE
`priority` is rejected as a spider argument

### ISSUE THREAD

**Issue by tanguilp** [scrapy/scrapyd#403] opened 2021-05-26 12:05 UTC
`priority` is silently deleted when used as a spider argument.

It should be accepted, or at least documented.

**Comment by jpmckinney** [comment] 2021-09-24 00:25
Aha, this is caused by #161. I suppose the solution will be documentation.

**Comment by atranou** [comment] 2022-02-24 08:38
Hello! I'd like to make this documentation note. Is it still open?

**Comment by jpmckinney** [comment] 2022-02-24 17:31
@atranou Yes, this issue is still open. Thank you!

**Comment by atranou** [comment] 2023-02-10 11:08
Hello! 
This issue is resolved and merged: https://github.com/scrapy/scrapyd/pull/433

**Comment by jpmckinney** [comment] 2023-02-10 15:30
Thank you!

**Closed by jpmckinney** 2023-02-10 15:30 UTC
Labels: topic: documentation
