### ISSUE TITLE
Finished jobs remain in the list and remain as running processes.

### ISSUE THREAD

**Issue by bleachyin** [scrapy/scrapyd#21] opened 2013-08-23 03:12 UTC
i use scrapyd to manage the job but when the job is finished ,it also exist in the joblist and the process of python is persistent there ,no i have a question, when i renew a ne w job it will existed forever if i won't kill the process, i need  help

**Comment by Digenis** [comment] 2016-01-21 15:48
I experienced stuck jobs too and so far I haven't managed to reproduce the issue.

**Comment by lunswor** [comment] 2016-03-09 15:59
I experience this too. Jobs remain in "Running" section. Normally I find this happens for me when running selenium within a spider and the WebDriver causes and exception.

**Comment by tedjt** [comment] 2016-04-11 22:06
@jayzeng  I'm seeing the first issue you described. The job is being canceled via the cancel.json endpoint, logs show it receiving the sig term (twice) and ending. The job is still in the list of jobs returns from listjobs.json for the project, but I can find now running python process for the crawl. Maybe add a poller that clears out jobs who's PID not longer exists? How can I track down why launcher._process_finished isn't being called?

**Comment by lunswor** [comment] 2016-04-11 22:11
@bleachyin @Digenis I experienced this issue too. For me it only occurred when I had uncaught exceptions in my spiders. Usually these were exceptions from Xvfb or the chromedriver crashing.
Even though the process for the spider was not running it was still seen in scrapyd until I killed the chromedriver/Xvfb.
Maybe another running process is blocking these tasks from moving to finished? Try checking for exceptions in the spider too.

**Comment by jayzeng** [comment] 2016-04-11 22:16
@tedjt second what @lunswor said, check the exception logs. I do dig the idea of "a poller that clears out jobs who's PID not longer exists" or something along that line.

**Comment by Digenis** [comment] 2016-04-12 06:07
@tedjt,
> The job is still in the list of jobs returns from listjobs.json for the project, but I can find now running python process for the crawl. 

Confirm that you forgot to type a "not" there because it's changes the meaning.

@jayzeng, I think such a poller is more of a hack.
Perhaps the runner has some trouble with children and signals.

@lunswor, can you point to the documentation you used for chromedriver?

**Comment by lunswor** [comment] 2016-04-12 08:05
@Digenis This is the basic concept I used, although this is for firefox. http://scraping.pro/use-headless-firefox-scraping-linux/ It may not be the case but I found chrome was more memory efficient in my case.

**Comment by Digenis** [comment] 2016-04-12 08:49
I'm talking about your usage of the webdriver inside scrapy.

**Comment by tedjt** [comment] 2016-04-12 16:51
@Digenis - should have been "I can find **No** running python process". So the process is in the list of running for scrapyd, but is not running on the system. I actually dug a little deeper and found a running process in another container that was keeping the _process_finished callback from triggering. I think all the scrapyd code is fine, the problem is just that sending sig TERM (even twice) to the scrapy process via the cancel.json endpoint never results in the process cleaning up. I've added an external watchdog to kill -9 stale scrapy processes so the scrapyd slot can be reclaimed.

**Comment by Digenis** [comment] 2016-04-12 17:20
But it's something that you can't reproduce in plain scrapy, only in scrapyd, right?

**Comment by Digenis** [comment] 2016-05-14 09:56
@bleachyin, @tedjt, @lunswor,
What databases do you use in your projects and in which scrapy component?
I suspect that an uncommitted transaction can cause this.

**Comment by tedjt** [comment] 2016-05-14 17:14
We are using whatever scrapyd uses out of the box. I'm pretty sure that's just in memory. We ended up adding a watchdog process that kills scrapy processes that our unknown to our downstream processors (things that consume Items). Works fine for us.

**Comment by Digenis** [comment] 2016-05-14 17:44
I'm talking about the scrapy project deployed to scrapyd.
The pipeline or whatsoever that passes the items to your downstream processor.

**Comment by Digenis** [comment] 2016-05-17 13:05
@bleachyin, @tedjt, @lunswor,
See my comment on https://github.com/scrapy/scrapyd/issues/75#issuecomment-219710925

**Comment by tedjt** [comment] 2016-05-17 16:02
Thanks @Digenis will look into it if we see it again. we use ZMQ to send jobs from our scrapy boxes to downstream services and it could be blocking on a recv call.

**Comment by Digenis** [comment] 2016-12-21 11:22
I assume that some singal handler for close_spider gets stuck.

I'm closing the issue because of insufficient info.

**Closed by Digenis** 2016-12-21 11:22 UTC
Labels: insufficient info

**Comment by 111qqz** [comment] 2018-12-26 11:49
same problem here.

**Comment by fuiyu** [comment] 2019-11-13 07:36
same problem here.

**Comment by error0g** [comment] 2022-11-14 06:00
same problem here.

**Comment by jpmckinney** [comment] 2022-11-14 14:33
Folks - you need to provide more info than "same problem". It is probably a bug in your own spiders, so you'll need to share the code for your Scrapy project, or a minimal sample to reproduce the error.
