### ISSUE TITLE
requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by singleDogZhanghan** [scrapy/scrapyd#354] opened 2019-08-28 06:12 UTC
it always happend,when i open the scrapyd service,and after some time ,if i do a request by the api,it raise the exception:requests.exceptions.ReadTimeout. However ,if i restart the service or just press "ctrl+c" ,it works again

**Comment by my8100** [comment] 2019-08-28 06:14
Can you post the related logs of Scrapyd?

**Comment by LianDiZhangHan** [comment] 2019-08-28 06:27
there is nothing in the related logs. and the raised exception is just the normal  requests exception.
"requests.exceptions.ReadTimeout: HTTPConnectionPool(host='*****', port=6800): Read timed out. (read timeout=5)'.
i think this seems to be asleep, but I don't know why.

**Comment by my8100** [comment] 2019-08-28 06:32
The logs you posted comes from the requests library, which has nothing to do with Scrapyd. 
You may need to modify the timeout argument in your code instead, e.g. `requests.get(url, timeout=30)`

**Comment by LianDiZhangHan** [comment] 2019-08-28 06:42
it doesn't work. if the problem happend,it will last a long time .
and  if the reason is the timeout,why after  i restart the service or press "ctrl + c" ,it can work normally

**Comment by my8100** [comment] 2019-08-28 07:31
What’s your Scrapyd version, is it running on the remote server, are there any pending jobs?

When the problem happens:
1. Test if the web UI is visitable. 
2. Try to use curl or any other tools to make the request on the Scrapyd server.

**Comment by LianDiZhangHan** [comment] 2019-08-28 07:46
My Scrapyd version is 1.2.1 and it is runing on the remote server. Usually after I started it for a while ,whether I schedule a job or not ，it has this problem.
when the problem happens, the web UI is visitable,and the test that requests remote server is normal.
However the curl  also can't work.

**Comment by my8100** [comment] 2019-08-28 07:51
How did you call the api (and which?) when the problem happened?
Run curl with the -v / --verbose option and post the full info.

**Comment by LianDiZhangHan** [comment] 2019-08-28 08:00
I call the list_jobs of ScrapydAPI when it happend. And,I don't know which command, can you give an example?

**Comment by my8100** [comment] 2019-08-28 08:05
On your Scrapyd server, run `curl -v http://localhost:6800/listjobs.json?project=myproject`

**Comment by LianDiZhangHan** [comment] 2019-08-28 08:13
the response is this ,and it doesn't look abnormal:
*   Trying ***...
* TCP_NODELAY set
* Connected to *** (***) port 6800 (#0)
> GET /listjobs.json?project=Spider_python HTTP/1.1
> Host: ***:6800
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: TwistedWeb/19.7.0
< Date: Wed, 28 Aug 2019 08:08:37 GMT
< Content-Type: application/json
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE
< Access-Control-Allow-Headers:  X-Requested-With
< Content-Length: 2919
<
{"node_name": "**", "status": "ok", "pending": [], "running": [], "finished": [**]}
* Connection #0 to host *** left intact

**Comment by my8100** [comment] 2019-08-28 08:16
Remember to run this command when the problem happens.

**Comment by LianDiZhangHan** [comment] 2019-08-28 08:31
Just when I tried to reproduce the problem, it may be that I modified the timeout argument in my code,  it did not make an error.If this problem happens again ,i'll run that command and contact you.Thank you very much for your answer.

**Comment by LianDiZhangHan** [comment] 2019-08-29 03:39
I am vrey sorry about that ,but that problem happens again. After I run your command, its response doesn't seem to have anything useful.

C:\Users\***>curl -v http://***:6800/listjobs.json?project=Spider_python
*   Trying ***...
* TCP_NODELAY set
* Connected to *** (***) port 6800 (#0)
> GET /listjobs.json?project=Spider_python HTTP/1.1
> Host: ***:6800
> User-Agent: curl/7.55.1
> Accept: */*
>

**Comment by LianDiZhangHan** [comment] 2019-08-29 03:49
I send the request(listjobs) every 10 seconds. From the record, it is clear that there has been some problem in the middle of the period. After that, I pressed crtl+c and it continued to work normally.

2019-08-29T11:23:32+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:23:32 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:23:42+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:23:42 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:23:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:23:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:24:02+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:24:02 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "curl/7.55.1"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:39:52+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:39:52 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:40:02+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:40:01 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:40:12+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:40:11 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:40:22+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:40:21 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"
2019-08-29T11:40:32+0800 [twisted.python.log#info] "****" - - [29/Aug/2019:03:40:32 +0000] "GET /listjobs.json?project=Spider_python HTTP/1.1" 200 631 "-" "python-requests/2.22.0"

**Comment by Digenis** [comment] 2019-08-30 04:47
Where do you press Ctrl-C?
In the shell running curl, requests or scrapyd?
If it's scrapyd, what happens after pressing Ctrl-C?
It's supposed to terminate, not unblock.
What version of scrapy are you using?
Have you tried different versions?

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:20
The version of scrapyd is 1.2.1.
I press Ctrl-C in the scrapyd, and when the problem happens,everything is useless,curl ,requests,or scrapyd.
Before I press Ctrl-C, the scrapyd just like sleeping,the work during that period cannot be seen.Until I press it firsttime,it can work again normally, and if I press Ctrl-C again ,it will be terminated.That means that when the scrapyd work normally ,everything is also normally ,and when the problem happens,I have no choice but to restart scrapy or press Ctrl-C.Set the timeout may not useful.

**Comment by my8100** [comment] 2019-08-30 05:24
Can you reproduce the problem in a new virtual environment?
Install Scrapyd only to keep it simple and pure.

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:28
I am sorry about that, the environment of scrapyd is already new. And I have tryed many times,the problem often occurs.

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:31
First of all, I can confirm that it is not a network problem, because when it happens, no matter how long it takes, I cannot request success.The only solution is to restart or press Ctrl-C.

**Comment by my8100** [comment] 2019-08-30 05:34
Can you run “pip freeze” or “pip list” and post the result?

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:37
Package            Version
------------------ ---------
asn1crypto         0.24.0
attrs              19.1.0
Automat            0.7.0
beautifulsoup4     4.8.0
bs4                0.0.1
certifi            2019.6.16
cffi               1.12.3
chardet            3.0.4
constantly         15.1.0
cryptography       2.7
cssselect          1.1.0
happybase          1.2.0
hyperlink          19.0.0
idna               2.8
incremental        17.5.0
lxml               4.4.1
parsel             1.5.2
pdfminer.six       20181108
pdfplumber         0.5.12
Pillow             6.1.0
pip                19.2.3
ply                3.11
pyasn1             0.4.6
pyasn1-modules     0.2.6
pycparser          2.19
pycryptodome       3.8.2
PyDispatcher       2.0.5
PyHamcrest         1.9.0
pyOpenSSL          19.0.0
pypiwin32          223
python-scrapyd-api 2.1.2
pywin32            224
queuelib           1.5.0
redis              3.3.8
requests           2.22.0
Scrapy             1.7.3
scrapy-redis       0.6.8
scrapyd            1.2.1
scrapyd-client     1.2.0a1
selenium           3.141.0
service-identity   18.1.0
setuptools         40.8.0
six                1.12.0
sortedcontainers   2.1.0
soupsieve          1.9.3
thriftpy2          0.4.4
Twisted            19.7.0
unicodecsv         0.14.1
urllib3            1.25.3
w3lib              1.21.0
Wand               0.5.6
zope.interface     4.6.0

**Comment by my8100** [comment] 2019-08-30 05:39
It’s not a pure env as scrapy-redis is listed.

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:43
The reason is scrapy-redis? All right,I'll delete it and try again. Wish the problem do not happen again. Thank you very much.

**Comment by my8100** [comment] 2019-08-30 05:44
Can you reproduce the problem in a new virtual environment?
Install Scrapyd only to keep it simple and pure.

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:50
sorry ,I don't have that kind of environment.I can only delete irrelevant packages as much as possible,and try it again.

**Comment by my8100** [comment] 2019-08-30 05:54
$ mkdir test
$ cd test
$ pip install virtualenv
$ virtualenv venv/test
$ source venv/test/bin/activate
(test) $ pip install scrapyd
(test) $ scrapd

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:57
What is the ip of the environment?

**Comment by my8100** [comment] 2019-08-30 05:58
It’s still 127.0.0.1:6800 or localhost:6800

**Comment by LianDiZhangHan** [comment] 2019-08-30 05:59
OK,I'm trying it.

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:02
It prompts me this:
'source' is not recognized as an internal or external command, operable program or batch file.
What shoud I do ?

**Comment by my8100** [comment] 2019-08-30 06:08
What's the OS of your server?
Can you post the logs of the process?

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:10
My  OS is windows10.
D:\test>pip install virtualenv
Collecting virtualenv
  Downloading 

Installing collected packages: virtualenv
Successfully installed virtualenv-16.7.4

D:\test>virtualenv venv/test
Using base prefix 'c:\\users\\zhanghan\\appdata\\local\\programs\\python\\python37'
New python executable in D:\test\venv\test\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

D:\test>source venv/test/bin/activate
'source' is not recognized as an internal or external command,
operable program or batch file.

**Comment by my8100** [comment] 2019-08-30 06:12
Isn't the Scrapyd running on a Linux server?

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:13
Sorry ,I run scrapyd on a windows server.
I use "venv\test\scripts\activate" successfully.
D:\test>venv\test\scripts\activate
(test) D:\test>

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:17
After that ,I run "pip install scrapyd",but it seems to install everything i had.


  Building wheel for pycparser (setup.py) ... done
  Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111066 sha256=5533867d361233d5a75debd8e4aeb33bfd0f689c10709984a9d51b11fbd385b5
  Stored in directory: C:\Users\zhanghan\AppData\Local\pip\Cache\wheels\f2\9a\90\de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built PyDispatcher pycparser
Installing collected packages: six, constantly, zope.interface, idna, hyperlink, attrs, Automat, incremental, PyHamcrest, Twisted, w3lib, PyDispatcher, pycparser, cffi, asn1crypto, cryptography, pyOpenSSL, cssselect, lxml, queuelib, parsel, pyasn1, pyasn1-modules, service-identity, Scrapy, scrapyd
Successfully installed Automat-0.7.0 PyDispatcher-2.0.5 PyHamcrest-1.9.0 Scrapy-1.7.3 Twisted-19.7.0 asn1crypto-0.24.0 attrs-19.1.0 cffi-1.12.3 constantly-15.1.0 cryptography-2.7 cssselect-1.1.0 hyperlink-19.0.0 idna-2.8 incremental-17.5.0 lxml-4.4.1 parsel-1.5.2 pyOpenSSL-19.0.0 pyasn1-0.4.6 pyasn1-modules-0.2.6 pycparser-2.19 queuelib-1.5.0 scrapyd-1.2.1 service-identity-18.1.0 six-1.12.0 w3lib-1.21.0 zope.interface-4.6.0

(test) D:\test>

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:19
I'm not sure that the environment is pure.

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:20
(test) D:\test>pip freeze
asn1crypto==0.24.0
attrs==19.1.0
Automat==0.7.0
cffi==1.12.3
constantly==15.1.0
cryptography==2.7
cssselect==1.1.0
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
lxml==4.4.1
parsel==1.5.2
pyasn1==0.4.6
pyasn1-modules==0.2.6
pycparser==2.19
PyDispatcher==2.0.5
PyHamcrest==1.9.0
pyOpenSSL==19.0.0
queuelib==1.5.0
Scrapy==1.7.3
scrapyd==1.2.1
service-identity==18.1.0
six==1.12.0
Twisted==19.7.0
w3lib==1.21.0
zope.interface==4.6.0

(test) D:\test>scrapyd
2019-08-30T14:19:46+0800 [-] Loading d:\test\venv\test\lib\site-packages\scrapyd\txapp.py...
2019-08-30T14:19:46+0800 [-] Scrapyd web console available at http://127.0.0.1:6800/
2019-08-30T14:19:46+0800 [-] Loaded.
2019-08-30T14:19:46+0800 [twisted.application.app.AppLogger#info] twistd 19.7.0 (d:\test\venv\test\scripts\python.exe 3.7.3) starting up.
2019-08-30T14:19:46+0800 [twisted.application.app.AppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2019-08-30T14:19:46+0800 [-] Site starting on 6800
2019-08-30T14:19:46+0800 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x000001DB79F49D68>
2019-08-30T14:19:46+0800 [Launcher] Scrapyd 1.2.1 started: max_proc=16, runner='scrapyd.runner'

**Comment by my8100** [comment] 2019-08-30 06:20
It's pure now.
No need to install any other packages.
Just go on to reproduce the problem.

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:29
There seems to be something wrong with this environment, and scrapy doesn't seem to be successful.

ConnectionRefusedError: [WinError 10061]
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002360B441860>: Failed to establish a new connection: [WinError 10061]

requests.exceptions.ConnectionError: HTTPConnectionPool(host='***', port=6800): Max retries exceeded with url: /listjobs.json?project=Spider_python (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002360B441860>: Failed to establish a new connection: [WinError 10061]

**Comment by my8100** [comment] 2019-08-30 06:32
Are http://127.0.0.1:6800/ and http://127.0.0.1:6800/daemonstatus.json reachable?

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:35
No, they have no response.

**Comment by my8100** [comment] 2019-08-30 06:37
Can you restart your PC and try again?

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:39
OK,please wait some minutes.

**Comment by LianDiZhangHan** [comment] 2019-08-30 06:56
http://127.0.0.1:6800/ and http://127.0.0.1:6800/daemonstatus.json is reachable.
But,when i run my project,the same problem happened.

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001FE81279EF0>: Failed to establish a new connection: [WinError 10061]

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='***', port=6800): Max retries exceeded with url: /listjobs.json?project=Spider_python (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FE81279710>: Failed to establish a new connection: [WinError 10061]

**Comment by my8100** [comment] 2019-08-30 06:59
What about curl?
Open another shell and run requests in the test env (`pip install requests` first).

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:03
It doesn't work.

C:\Users\zhanghan>curl http://***:6800/listjobs.json?project=myproject
curl: (7) Failed to connect to *** port 6800: Connection refused

C:\Users\zhanghan>cd /d d:\test

d:\test>venv\test\scripts\activate

(test) d:\test>curl http://***:6800/listjobs.json?project=myproject
curl: (7) Failed to connect to *** port 6800: Connection refused

(test) d:\test>

**Comment by my8100** [comment] 2019-08-30 07:08
(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/daemonstatus.json'); print(r.json())"
(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/listjobs.json?project=myproject'); print(r.json())"

**Comment by my8100** [comment] 2019-08-30 07:11
Why are you hiding the IP, isn't it '127.0.0.1' or 'localhost'?

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:15
I am using real ip.
Because I can't connect to it ,I could not deploy my project on that server.


(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/daemonstatus.json'); print(r.json())"
{'node_name': 'LD-DT-1915', 'status': 'ok', 'pending': 0, 'running': 0, 'finished': 0}


(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/listjobs.json?project=***'); print(r.json())"
{'node_name': 'LD-DT-1915', 'status': 'error', 'message': "'***'"}

**Comment by my8100** [comment] 2019-08-30 07:17
Note that for remote access, you have to manually set 'bind_address = 0.0.0.0' in [the configuration file of Scrapyd](https://scrapyd.readthedocs.io/en/latest/config.html#example-configuration-file) and restart Scrapyd to make it visible externally.

**Comment by my8100** [comment] 2019-08-30 07:19
> I am using real ip.
> Because I can't connect to it ,I could not deploy my project on that server.

Why don't you create the virtual env on your server???

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:20
I just created the virtual environment on that server.

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:21
My company thinks these things are secret, so I have to hide

**Comment by my8100** [comment] 2019-08-30 07:22
I was asking you to create the virtual env on your server for debugging the problem of Scrapyd.
Do you understand???

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:25
I have created the virtual env on my server.But the same code can't run beacuse of the same problem.

**Comment by my8100** [comment] 2019-08-30 07:27
No one can help you if no useful info is provided.

**Comment by my8100** [comment] 2019-08-30 07:30
What code?

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:31
I am sorry . I am trying to run curl on my server by using '127.0.0.1',and it doesn't work.


(test) d:\test>curl http://localhost/listjobs.json?project=Spider_python
curl: (7) Failed to connect to localhost port 80: Connection refused

(test) d:\test>curl http://127.0.0.1/listjobs.json?project=Spider_python
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

**Comment by my8100** [comment] 2019-08-30 07:34
> ```
> (test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/daemonstatus.json'); print(r.json())"
> (test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/listjobs.json?project=myproject'); print(r.json())"
> ```

If you have created the virtual env on your Linux server and run Scrapyd in that env,
run the code above directly on your server, but not on win10.

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:37
Sorry, I don't have the Linux server.Is there some problems in the win10?

**Comment by my8100** [comment] 2019-08-30 07:38
"I just created the virtual environment on that server."
What do you mean by 'server', the win10 PC???

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:40
yes

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:40
Does scrapyd have to run on Linux?

**Comment by my8100** [comment] 2019-08-30 07:41
New a file 'scrapyd.conf' in d:\test:
```
[scrapyd]
bind_address = 0.0.0.0
```
Restart Scrapyd, then you can visit Scrapyd via the actual IP of your PC.

**Comment by my8100** [comment] 2019-08-30 07:44
> I am sorry . I am trying to run curl on my server by using '127.0.0.1',and it doesn't work.
> 
> (test) d:\test>curl http://localhost/listjobs.json?project=Spider_python
> curl: (7) Failed to connect to localhost port 80: Connection refused
> 
> (test) d:\test>curl http://127.0.0.1/listjobs.json?project=Spider_python
> curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused

The default port is 6800:
```
curl http://127.0.0.1:6800/listjobs.json?project=Spider_python
```

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:49
How could I deploy my project in the viturl env , or if I need to deploy my project on that PC.

**Comment by LianDiZhangHan** [comment] 2019-08-30 07:50
This command is normal.

(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/daemonstatus.json'); print(r.json())"
{'node_name': 'LD-DT-1915', 'status': 'ok', 'pending': 0, 'running': 0, 'finished': 0}

**Comment by my8100** [comment] 2019-08-30 07:50
Just as usual.

**Comment by my8100** [comment] 2019-08-30 07:54
The virtual env is only isolating the Python interpreter and package dependencies.

**Comment by my8100** [comment] 2019-08-30 08:00
Is the IP of your win10 PC static or dynamic?

**Comment by LianDiZhangHan** [comment] 2019-08-30 08:01
It is static.

**Comment by LianDiZhangHan** [comment] 2019-08-30 08:01
Sorry ,I can't deploy my project ,it raise many ModuleNotFoundErrors.

**Comment by my8100** [comment] 2019-08-30 08:05
In order to reproduce the problem, deploy a simple project without dependence.

**Comment by LianDiZhangHan** [comment] 2019-08-30 08:07
OK

**Comment by LianDiZhangHan** [comment] 2019-08-30 08:23
I create a new simple project and deploy it . And it looks good .Next, do I need to try to reproduce the problem?


(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/listjobs.json?project=test_scrapyd'); print(r.json())"
{'node_name': 'LD-DT-1915', 'status': 'ok', 'pending': [], 'running': [], 'finished': []}

(test) d:\test>python -c "import requests; r = requests.get('http://127.0.0.1:6800/daemonstatus.json'); print(r.json())"
{'node_name': 'LD-DT-1915', 'status': 'ok', 'pending': 0, 'running': 0, 'finished': 0}

**Comment by my8100** [comment] 2019-08-30 13:29
Deleted meaningless conversations.

**Comment by jpmckinney** [comment] 2021-09-23 20:45
Closing as the support request seems to have hit a dead end.

**Closed by jpmckinney** 2021-09-23 20:45 UTC
Labels: type: question
