### ISSUE TITLE
Poller should fill all available slots

### ISSUE THREAD

**Issue by Tarliton** [scrapy/scrapyd#173] opened 2016-08-23 21:24 UTC
Today we can choose "poll_interval", "max_proc" and "max_proc_per_cpu". "max_proc" and "max_proc_per_cpu" are for limiting a maximum of jobs that can be running.

If "poll_interval" is high that maximum would never be reached. That happens because after each poll interval we start only one job.

E.g.: poll_interval = 30 and some spider takes about 2 minutes to finish. The maxium jobs that would run in this case is 4~5, no matter what "max_proc" and "max_proc_per_cpu" values are.

Maybe it should have an option "jobs_to_poll". With that we could choose how many jobs to poll each time, instead of only one.

What you guys think about that?

Thank you

**Comment by Digenis** [comment] 2016-08-24 14:15
I'd expect developers in this case to write spiders
that don't close but stay open to crawl on demand
but I do think that your concern is a valid.
However I'm not the appropriate person to look into it.
Someone more familiar with twisted can have a look.

**Comment by Digenis** [comment] 2016-11-02 15:50
Actually it makes sense for the poller
to poll for exactly as many spiders as the amount of free slots.
This should be easier if the project queues are unified in a single db(and/or table)
as I suggest in #187

**Comment by Digenis** [comment] 2016-12-07 12:01
By the way, you can set the poller to poll on a sub-second interval.
I'll add this to the documentation now.

**Comment by jpmckinney** [comment] 2022-05-13 15:49
Closing as duplicate of #187

**Comment by jpmckinney** [comment] 2024-07-23 16:33
Re-opening as this is actually separatable from the other issues.

Poller.poll knows when all slots are full by checking `dq.waiting`, and it knows when it has no pending jobs to return by checking `message is not None`. So, we should be able to just add these checks into loops.

**Comment by jpmckinney** [comment] 2024-07-24 03:50
FWIW, I can't replicate this issue. I set `poll_interval = 0.1` and scheduled 100 jobs in a loop.

**Closed** 2024-07-24 04:00 UTC
Labels: type: enhancement, topic: scheduling
