### ISSUE TITLE
KeyError on listjobs request after scrapyd restart

### ISSUE THREAD

**Issue by Kookabura** [scrapy/scrapyd#233] opened 2017-05-25 14:05 UTC
Seems `self.root.poller.queues` is not updated on scrapyd daemon start. It leads to error on listjobs and schedule requests for all deployed projects before new scrapyd-deploy.
For fixing listjobs request I've added `self.root.poller.update_projects()` before line 124 in webservice.py https://github.com/scrapy/scrapyd/blob/master/scrapyd/webservice.py#L124.
I'm not sure that's the best deal but it works.

This is the error that I got:
```
2017-05-25T16:21:15+0300 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib64/python3.4/site-packages/twisted/web/http.py", line 1906, in allContentReceived
            req.requestReceived(command, path, version)
          File "/usr/lib64/python3.4/site-packages/twisted/web/http.py", line 771, in requestReceived
            self.process()
          File "/usr/lib64/python3.4/site-packages/twisted/web/server.py", line 190, in process
            self.render(resrc)
          File "/usr/lib64/python3.4/site-packages/twisted/web/server.py", line 241, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/usr/lib/python3.4/site-packages/scrapyd/webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "/usr/lib/python3.4/site-packages/scrapyd/utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "/usr/lib64/python3.4/site-packages/twisted/web/resource.py", line 250, in render
            return m(request)
          File "/usr/lib/python3.4/site-packages/scrapyd/webservice.py", line 124, in render_GET
            queue = self.root.poller.queues[project]
        builtins.KeyError: 'medse'
```

**Comment by Kookabura** [comment] 2017-05-25 14:10
The edited file is here https://github.com/Kookabura/scrapyd/blob/master/scrapyd/webservice.py#L124

**Comment by Digenis** [comment] 2017-05-26 09:44
This shouldn't be necessary
as update_projects is called when the daemon starts.

Please, write down all the steps you take to reproduce it.
I never had such issues when restarting scrapyd.

**Comment by Kookabura** [comment] 2017-05-26 10:24
That's strange because I noticed that update_projects is called in scheduler.py as well but self.queues is empty schedule.json request. I had to add self.update_projects() in schedule function. It appears to be non working within __init__ function.

Steps to reproduce:
- start scrapyd daemon
- `scrapyd-deploy` from the project folder
- listjobs and schedule are working fine at this moment
- restart scrapyd daemon
- listjobs and schedule requests are failed with the error in /var/log/scrapyd from my first post.

I've tried this on two different systems. Both are CentOs. The first one is:
```
[root@srv1]$ cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@srv1]$ scrapyd --version
twistd (the Twisted daemon) 17.1.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
```
The second on is:
```
[root@srv2 ~]$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@srv2 ~]$ scrapyd --version
twistd (the Twisted daemon) 16.6.0
Copyright (c) 2001-2016 Twisted Matrix Laboratories.
See LICENSE for details.
```

**Comment by Digenis** [comment] 2017-05-26 10:45
Could it be #70?
What init/systemd script do you use?
In which directory do you run scrapyd?

**Comment by Kookabura** [comment] 2017-05-26 11:07
Yes, that was the problem. Thank you.
I didn't use --rundir. Instead I set up default directory when created a user. I thought that the process start working in this directory and it worked before restarting the daemon.
I've added `WorkingDirectory` to service definition now and it works as expected. Have a good day:).

**Comment by Digenis** [comment] 2017-05-26 11:40
OK, closing this as a duplicate of #70.

**Closed by Digenis** 2017-05-26 11:40 UTC
Labels: duplicate

**Comment by padaliyajay** [comment] 2020-06-03 09:34
> Yes, that was the problem. Thank you.
> I didn't use --rundir. Instead I set up default directory when created a user. I thought that the process start working in this directory and it worked before restarting the daemon.
> I've added `WorkingDirectory` to service definition now and it works as expected. Have a good day:).

I have also the same problem, can you help me to fix it. how to use --rundir
