### ISSUE TITLE
Wrong type adaption for BLOB in scrapyd sqlite3 utils

### ISSUE THREAD

**Issue by dkachan1941** [scrapy/scrapyd#150] opened 2016-05-19 07:35 UTC
When I execute

`curl http://localhost:6800/schedule.json -d project=default -d spider=spider1`

I go to scrapyd console and I see the Exception:

```
[-] Unhandled Error
Traceback (most recent call last):
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/poller.py", line 23, in poll
    msg = yield maybeDeferred(q.pop)
--- <exception caught here> ---
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/spiderqueue.py", line 21, in pop
    return self.q.pop()
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/sqlite.py", line 119, in pop
    return self.decode(msg)
  File "/home/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/sqlite.py", line 170, in decode
    return json.loads(text)
  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
exceptions.ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
```

After that I can't run next Spider, I get
`
{"status": "error", "message": "No JSON object could be decoded", "node_name": "spider-test2"}`

How to determine what that error is related to?

**Comment by Digenis** [comment] 2016-05-19 12:05
@dkachan1941, try deleting your database directory and starting scrapyd again.

If this doesn't work,
we have to dig deeper and see why it gets corrupted.
In this case replace line 119 in `/home/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/sqlite.py`
from `return self.decode(msg)` to the following:
```python
try:
    return self.decode(msg)
except:
    from twisted.python import log
    log.msg("Can't decode json obj: %r" % msg, level=log.ERROR)
    raise
```
And trigger the error again.
Then paste the log here.

**Comment by dkachan1941** [comment] 2016-05-19 13:05
Thank you for your response. I removed all db folders, tried again, but it didn't succeed.
Then I logged that part. I got next result - 
[Can't decode json obj: u'{\x00"\x00_\x00j\x00o\x00b\x00"\x00:\x00 \x00"\x006\x005\x001\x009\x005\x007\x007\x006\x001\x00d\x00c\x002\x001\x001\x00e\x006\x00b\x00b\x001\x00b\x000\x000\x005\x000\x005\x006\x00a\x004\x000\x001\x00a\x003\x00"\x00,\x00'
2016-05-19 16:05:43+0300 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
	    return _inlineCallbacks(None, gen, Deferred())
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
	    result = g.send(result)
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/poller.py", line 23, in poll
	    msg = yield maybeDeferred(q.pop)
	--- <exception caught here> ---
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/spiderqueue.py", line 21, in pop
	    return self.q.pop()
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/sqlite.py", line 120, in pop
	    return self.decode(msg)
	  File "/home/spider/scrapyV1/venv/lib/python2.7/site-packages/scrapyd/sqlite.py", line 175, in decode
	    return json.loads(text)
	  File "/usr/local/lib/python2.7/json/__init__.py", line 338, in loads
	    return _default_decoder.decode(s)
	  File "/usr/local/lib/python2.7/json/decoder.py", line 366, in decode
	    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	  File "/usr/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
	    obj, end = self.scan_once(s, idx)
	exceptions.ValueError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)](url)

We got job id ( but without squiggle bracket) - {"_job": "f27cb6721dc111e68fab005056a401a3",

**Comment by Digenis** [comment] 2016-05-19 13:31
The json object looks like it's encoded in BOM-less UTF-16 (maybe).

What OS are you using?
Perhaps scrapyd is accidentally using sqlite in a platform specific way.
Run sqlite3 --version

**Comment by dkachan1941** [comment] 2016-05-19 13:37
Centos 6.5
sqlite3 --version
3.6.20

**Comment by Digenis** [comment] 2016-05-19 15:04
I can't manage to reproduce it.
There are some things you can try
like adding an encoding pragma:
```diff
 class SqlitePriorityQueue(object):
     """SQLite priority queue. It relies on SQLite concurrency support for
     providing atomic inter-process operations.
     """
 
     def __init__(self, database=None, table="queue"):
         self.database = database or ':memory:'
         self.table = table
         # about check_same_thread: http://twistedmatrix.com/trac/ticket/4040
         self.conn = sqlite3.connect(self.database, check_same_thread=False)
+       self.conn.execute('PRAGMA encoding = "UTF-8";')
         q = "create table if not exists %s (id integer primary key, " \
             "priority real key, message blob)" % table
         self.conn.execute(q)
```
(or other encodings from https://www.sqlite.org/pragma.html#pragma_encoding)
Then delete again `default.db` and run scrapyd.

**Comment by dkachan1941** [comment] 2016-05-20 08:35
No way. I tried all PRAGMAs, tried yo reinstall sqlite3 (seems like Centos6.5 doesn't support sqlite3 > 3.6.20). - no Results.
 Then I tried to install same versions scrapy&scrapyd on Ubuntu - it works.
I decided to use scrapy.crawler.CrawlerProcess instead of scrapyd for parallel running. Is there a difference?

**Comment by Digenis** [comment] 2016-05-20 08:54
Yes, you'll have to manage projects, spiders and spider runs on your own
but it shouldn't be hard at all.

Perhaps you can get help from some other community member like @boogheta who uses CentOS.

**Comment by boogheta** [comment] 2016-05-20 09:38
maybe a problem with the locales installed and set on the machine?

**Comment by dkachan1941** [comment] 2016-05-20 10:40
```
I set locales to "LANG=en_US.UTF-8"

# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Result the same.
```

**Comment by Digenis** [comment] 2016-05-20 11:29
Can you reproduce this without scrapyd?

```python
import sqlite3, json
conn = sqlite3.connect('/tmp/corrupt.db', check_same_thread=False)
q = '''
create table if not exists test (id integer primary key, 
priority real key, message blob)'''
conn.execute(q)

qi = "insert into test (priority, message) values (?,?)"
qs = "select id, message from test order by priority desc limit 1" 
qd = "delete from test where id=?"

for enc in [(lambda i: i), json.dumps, lambda w: json.dumps({w: w})]:
    for msg in ['ascii', u'unicode \N{SNOWMAN}']:
        print 'testing %r, %r' % (enc, msg)
        conn.execute(qi, (0.0, enc(msg)))
        id_, msg = conn.execute(qs).fetchone()
        conn.execute(qd, (id_,))
        conn.commit()
        print repr([id_, msg])
```

**Comment by dkachan1941** [comment] 2016-05-20 11:53
python scrapyd_test.py 
testing <function <lambda> at 0x7ff8688c8c80>, 'ascii'
[1, u'a\x00s\x00c']
testing <function <lambda> at 0x7ff8688c8c80>, u'unicode \u2603'
Traceback (most recent call last):
  File "scrapyd_test.py", line 16, in <module>
    id_, msg = conn.execute(qs).fetchone()
sqlite3.OperationalError: Could not decode to UTF-8 column 'message' with text '����������������☃'

**Comment by Digenis** [comment] 2016-05-20 12:25
What if you skip `(lambda i: i),` from the list?
json should work since it returns bytes.
(you'll need to delete the db too.

**Comment by dkachan1941** [comment] 2016-05-20 12:38
`for enc in [json.dumps, lambda w: json.dumps({w: w})]:`
got:
`[1, u'"\x00a\x00s\x00c']
testing <function dumps at 0x7f9d080c7b18>, u'unicode \u2603'
[1, u'"\x00u\x00n\x00i\x00c\x00o\x00d\x00e\x00']
testing <function <lambda> at 0x7f9d080c7c80>, 'ascii'
[1, u'{\x00"\x00a\x00s\x00c\x00i\x00i\x00"\x00:\x00']
testing <function <lambda> at 0x7f9d080c7c80>, u'unicode \u2603'
[1, u'{\x00"\x00u\x00n\x00i\x00c\x00o\x00d\x00e\x00 \x00\\\x00u\x002\x006\x000\x003\x00"\x00:\x00']`

**Comment by Digenis** [comment] 2016-05-20 13:01
Probably a bug in sqlite or the python module.
Try this:
```diff
diff --git a/scrapyd/sqlite.py b/scrapyd/sqlite.py
index 69f44a6..3d9cf80 100644
--- a/scrapyd/sqlite.py
+++ b/scrapyd/sqlite.py
@@ -93,6 +93,7 @@ class SqlitePriorityQueue(object):
         self.table = table
         # about check_same_thread: http://twistedmatrix.com/trac/ticket/4040
         self.conn = sqlite3.connect(self.database, check_same_thread=False)
+        self.conn.text_factory = bytes
         q = "create table if not exists %s (id integer primary key, " \
             "priority real key, message blob)" % table
         self.conn.execute(q)
```

**Comment by dkachan1941** [comment] 2016-05-20 13:19
Finally!
But you also need to add 
`self.conn.text_factory = bytes`
to SqliteDict class after connect creation.
Now everything works perfectly! Thank you!

**Comment by Digenis** [comment] 2016-05-20 14:05
Absurd! The column is of BLOB type.
I'm afraid that this can't be fixed in a backwards compatible way
but I'll look further into it. I'll set up a CentOS vm when I have the time.

**Comment by Digenis** [comment] 2016-05-20 14:14
http://bugs.python.org/issue7723

**Comment by Digenis** [comment] 2016-05-20 14:19
@dkachan1941, do you mind testing my snippet again in python3 on the same system?

**Comment by dkachan1941** [comment] 2016-05-20 15:05
I don't mind. But that sistem is at my work space and I'll be there on monday. 
But scrapyd works only with python 2.7, Doesn't it?

**Comment by Digenis** [comment] 2016-05-20 15:08
scrapyd works only on python3.
I meant this snippet https://github.com/scrapy/scrapyd/issues/150#issuecomment-220582206

**Comment by dkachan1941** [comment] 2016-05-20 15:13
Yep, I'll test that snippet on monday. It's no bother.

**Comment by dkachan1941** [comment] 2016-05-20 15:20
And the spider name defined using unicode string, yes.

**Comment by Digenis** [comment] 2016-05-20 15:49
> The json object looks like it's encoded in BOM-less UTF-16 (maybe).

It's not an encoding issue, I managed to reproduce it (in python2):
`str(buffer(u'abc'))` returns `'a\x00\x00\x00b\x00\x00\x00c\x00\x00\x00'`
on a 64 bit architecture.

I'm still far from fixing this.

**Comment by dkachan1941** [comment] 2016-05-23 05:25
Hi! I can not test your script cause python3 returns error:
`>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'`

**Comment by Digenis** [comment] 2016-05-23 06:57
Perhaps you have a broken installation.
Doesn't CentOS provide a package for python?
How did it end up in /usr/local? (both versions)

**Comment by Digenis** [comment] 2016-05-24 13:21
I'm setting up a CentOS 6.5 vm to test this.
I decided to use `sqlite3.Binary` which is defined by the [db-api2 specs for python](https://www.python.org/dev/peps/pep-0249/#binary).
Maybe this will make the sqlitequeue incompatible with leftover rows,
I'll have to test on a combination of platforms and pythons.

**Comment by Digenis** [comment] 2016-05-26 13:26
I didn't manage to reproduce it on Centos6.5
with Python-2.6.6 scrapyd-1.1 scrapy-0.18
nor with Python-2.7.6 scrapyd-1.1 scrapy-1.1
What python-2.7 minor version did you use
and how did you install it?
How did you install sqlite-devel?

**Comment by dkachan1941** [comment] 2016-05-27 05:45
Python 2.7.9
I don't remember how I installed sqlite. It was about 2 years ago, but I have sqlite-devel-3.6.20-1.el6_7.2.x86_64

**Comment by Digenis** [comment] 2016-05-27 15:26
I used the same sqlite3 version.
I tried again with python-2.7.9 and I still can't reproduce it.
Also, I just realized that you are on a x86_64 (I used a 32 bit centos image).
You better remove `/usr/local/lib/python-2.7/`, `~/.cache/pip/`
reinstall python-2.7 and your virtualenv.

I'm sure scrapyd.sqlite is using sqlite3 incorrectly
as I said in https://github.com/scrapy/scrapyd/issues/150#issuecomment-221266137
but I don't want to blindly make changes on the stable branch
without reproducing the environment that introduced the bug.

**Comment by Digenis** [comment] 2016-06-08 12:49
After a personal exchange
we figured that the database file is ok.
The problem only occurs when retrieving rows.

**Comment by Digenis** [comment] 2016-11-03 09:46
@dkachan1941 you can install the new bugfix release with
 `pip install git+https://github.com/scrapy/scrapyd.git@1.1`
Does this fix the issue?

**Comment by Digenis** [comment] 2016-12-16 14:48
I'm closing this.
If it persists, please reopen the issue.

**Closed by Digenis** 2016-12-16 14:48 UTC
Labels: bug, insufficient info
