### ISSUE TITLE
Is there a way to show the items count in the jobs list webpage?

### ISSUE THREAD

**Issue by Jgaldos** [scrapy/scrapyd#239] opened 2017-08-08 16:57 UTC
Hi, I am new in scrapy and scrapyd, now I'm running the project with no problems but I want to know if there is a way to show the items count in the job webpage, I want to have more information about each running spiders so I added the spider arguments and now I looking for a way to count the items per spider and show it independently from the item log, maybe using a signal o something? Thank for your help

**Comment by Digenis** [comment] 2017-08-14 11:00
@Jgaldos, I'm not sure if there's a direct way. You can write a custom scrapy extension.
I need to catch up with scrapy's recent developments to see if there's something new built-in.

It should be possible to access the crawler stats through the telnet console
but it's kind of a backdoor that you wouldn't want to expose.

You said you added the spider arguments.
Do you mean you display some spider arguments in the jobs webpage?

**Comment by Jgaldos** [comment] 2017-08-16 14:28
@Digenis yeah I display the arguments in the jobs webpage, I was thinking of using the spider telnet port but it's deactivated because when I launched sevaral spiders with a script some showed a telnet error saying that the port is already in use, is other way to get info from the spider without the telnet port? or maybe is there a way to securre the telnet port?

**Comment by Digenis** [comment] 2017-08-16 16:00
The work it'll take you to secure it is at least as much as it will take to write it your own plugin
(but probably more).

**Comment by Jgaldos** [comment] 2017-08-16 23:00
Do you have any idea how to get info from the spider without using the telnet port?, What I want to do is show stat info on the job web page.

**Comment by my8100** [comment] 2018-10-03 14:08
try this https://github.com/my8100/scrapydweb

**Comment by jpmckinney** [comment] 2022-05-13 16:00
Duplicate of #39, except this is furthermore about updating the jobs table with the stats of running crawls.

As described above, in the meantime, you can write a Scrapy extension using the [item_scraped](https://docs.scrapy.org/en/latest/topics/signals.html) signal (or another signal, as relevant), to update whatever database you like. Otherwise, Scrapyd gives you access to the crawl's log file, which you can parse to get the number of items scraped.

Also closing as this feature request has not attracted additional interest since 2017.

**Closed by jpmckinney** 2022-05-13 16:00 UTC
Labels: type: enhancement

**Comment by Digenis** [comment] 2022-08-15 15:02
@jpmckinney
I'm not familiar with the recent developments in scrapyd
but since you solved #12
I suppose you can use the same db to store the scrapy stats when spiders exit.

However I don't think it's possible without adding code to every scrapy project or scrapy itself.
It can be an extension imported from scrapyd in the project: scrapyd.integrations.CollectStats
or an extension built in scrapy that just gets activated by a setting in scrapyd.
I'm sure lot's of users would benefit from the second one even without scrapyd,
there are probably many users' extensions that dump the stats for logstash to upload to elastic.

Then it's up to scrapyd to decide which to store.
All of them are useful but you have to consider the limits of sqlite3.
It's true that item_scraped_count is of special interest,
e.g in postgres I'm currently considering adding a GENERATED STORED column for it if the the rest is TOAST

**Comment by jpmckinney** [comment] 2022-08-16 18:17
In Scrapy, you can store stats at the end of a crawl like so:

1. Subclass [StatsCollector](https://github.com/scrapy/scrapy/blob/master/scrapy/statscollectors.py)
3. Override `_persist_stats` (or `close_spider`) to store statistics wherever you like
4. Set [STATS_CLASS](https://docs.scrapy.org/en/latest/topics/settings.html#stats-class) to your subclass

While Scrapyd *could* offer solutions, I'd rather keep the feature set as it is.

So, storing stats is more of a Scrapy documentation problem than a Scrapyd problem.
