### ISSUE TITLE
Run a script when job finishes

### ISSUE THREAD

**Issue by mazzespazze** [scrapy/scrapyd#395] opened 2020-12-19 09:50 UTC
Hello, after reading the documentation I couldn't find if it is possible to run a function/script as soon as a job is finished. 

Let's say my data flow requires to:

1. Launch a spider and scrape some web pages
2. Wait until the job is finished
3. Apply a script on the crawled data

Is there any way today to be notified by **scrapyd** that a job is done? I know there exists the API "listjobs", but then I need to keep polling the API until the job is labelled finish, and then execute my script. Can this be turned the other way, by scrapyd notifying that a job is finished?

**Comment by psdon** [comment] 2021-01-05 19:16
This is also my biggest problem right now. Any insights @mazzespazze

**Comment by mazzespazze** [comment] 2021-01-07 17:27
@psdon I wrote my own "routine". Meaning that I wrote a bash script that periodically checks the list of jobs finishes/done and every time a job is labeled "finished", I apply my script and then force the removal of the job from the finished list. 

It is probably not the most elegant way, but it is quite practical. Hope it helps

**Comment by billsteve** [comment] 2021-01-10 15:49
close_spider in pipeline ??

**Comment by psdon** [comment] 2021-02-08 18:52
yeah, close_spider is the answer to my problem

**Comment by Digenis** [comment] 2021-04-09 17:03
Duplicate of #55

**Closed by Digenis** 2021-04-09 17:03 UTC
Labels: duplicate, enhancement
