### ISSUE TITLE
log encoding and charset header

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#342] opened 2019-06-23 19:42 UTC
Currently scrapy uses utf-8 in the logs by default.
Scrapyd's responses when sending the logs don't set a charset
and users are presented with gibberish instead of non-ascii text.

Many decisions in scrapyd are already based on scrapy's default configuration
and, anyway, anyone changing the utf-8 default to a different encoding is asking for trouble.

**Comment by jpmckinney** [comment] 2021-09-23 20:52
Is the solution to set a charset for the log file?

Or is this a non-issue? I can read logs that contain UTF-8 characters, whether in the browser or on the command-line, and they are not gibberish.

**Comment by jpmckinney** [comment] 2022-05-13 16:39
Closing as cannot reproduce the issue.

**Closed by jpmckinney** 2022-05-13 16:39 UTC
Labels: status: invalid, type: discussion

**Comment by Digenis** [comment] 2022-08-15 15:42
It was the browsers' encoding detection that wasn't favoring utf8 as much as it should.
Maybe now it does.
